workflows:
  # android-workflow:
  #   name: Android Workflow
  #   max_build_duration: 60
  #   environment:
  #     flutter: stable
  #     android_signing:
  #       keystore: $CM_KEYSTORE
  #       keystore_password: $CM_KEYSTORE_PASSWORD
  #       key_alias: $CM_KEY_ALIAS
  #       key_password: $CM_KEY_PASSWORD
  #     vars:
  #       PACKAGE_NAME: "com.example.yourapp" # あなたのアプリのパッケージ名に置き換えてください
  #       GOOGLE_PLAY_TRACK: "internal" # デプロイするトラック（internal、alpha、beta、productionなど）
  #   scripts:
  #     - name: Install dependencies
  #       script: flutter pub get
  #     - name: Run tests
  #       script: flutter test
  #     - name: Build APK
  #       script: |
  #         BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
  #         flutter build apk --release --build-name=1.0.$BUILD_NUMBER --build-number=$BUILD_NUMBER
  #   artifacts:
  #     - build/app/outputs/flutter-apk/app-release.apk
  #   publishing:
  #     google_play:
  #       credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
  #       track: $GOOGLE_PLAY_TRACK
  #       submit_as_draft: true
  #     email:
  #       recipients:
  #         - your_email@example.com
  #       notify:
  #         success: true
  #         failure: true