openapi: 3.0.0  # OpenAPIのバージョンを指定
info:
  title: utrack API  # APIのタイトル
  description: this API is utrack API  # APIの説明
  version: 1.0.0  # APIのバージョン
servers:
  - url: https://api.example.com/v1  # 基本となるサーバーのURL
    description: Production server (uses live data)

paths:
  /classes:  # エンドポイント定義
    get:
      summary: Retrieve a list of classes
      description: Retrieve a list of all classes in the system.
      responses:
        '200':
          description: A list of classes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Class'

  /users/{userid}/tasks:
    get:
      summary: Retrieve tasks for a specific user
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '200':
          description: A list of tasks for the user
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
                required:
                  - userId
                  - tasks

  /users/{userid}/classes:
    get:
      summary: Retrieve classes for a specific user
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '200':
          description: specific user class
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                  classes:
                    type: array
                    items: 
                      $ref: '#/components/schemas/Class'
                required:
                  - userId
                  - classes
    post:
      summary: Register a class for a user
      parameters:
        - $ref: '#/components/parameters/UserId'
      requestBody:
        description: The classes to be registered for the user
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                class_ids:
                  type: array
                  items:
                    type: string
                  description: The list of class IDs to register for the user
              required:
                - class_ids
      responses:
        '201':
          description: Classes successfully registered for the user
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                    description: The ID of the user
                  registered_classes:
                    type: array
                    items:
                      $ref: '#/components/schemas/Class'
                required:
                  - userId
                  - registered_classes
        '400':
          description: Invalid request (e.g., invalid class IDs or user not found)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message detailing what went wrong
                required:
                  - error

components:
  parameters:
    UserId:
      in: path
      name: userid
      required: true
      schema:
        type: string
      description: タスクを取得する対象のユーザーID

  schemas:
    Task:
      type: object
      required:
        - id
        - name
        - deadline
        - class_id
        - how_to_submit
        - state
      properties:
        id:
          type: string
          description: Unique identifier for the task
        class_id:
          type: string
          description: The IDs of the classes associated with the task
        name:
          type: string
          description: The name of the task
        deadline:
          type: string
          format: date-time
          description: The deadline for the task (in ISO 8601 format)
        how_to_submit:
          type: string
          description: Instructions on how to submit the task
        state:
          type: string
          enum: [pending, completed, overdue]
          description: The current state of the task

    Class:
      type: object
      required:
        - id
        - name
        - professor
        - place
        - period
        - day_of_week
        - semester
        - year
      properties:
        id:
          type: string
          description: Unique identifier for the class
        name:
          type: string
